IMAGE_VERSION=2.1.2
TORCH_VERSION=2.7.0
CUDA_VERSION=12.6.0
UBUNTU_VERSION=24.04
LLVM_VERSION=21
IMAGE_TAG=v${IMAGE_VERSION}-torch${TORCH_VERSION}-cuda${CUDA_VERSION}-ubuntu${UBUNTU_VERSION}
IMAGE_NAME=jamesnulliu/deeplearning:${IMAGE_TAG}